# Builds the docs and deploys them to the GitHub pages docs site
# Based on https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy Docs

on: [pull_request]

jobs:
  deploy:
    name: Deploy Docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install and Build
        uses: ./.github/actions/install-and-build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to
          FOLDER: doc/_build/html # The folder the action should deploy
          CLEAN: true # Automatically remove deleted files from the deploy branch
